### ISSUE TITLE
Ignores fields after successful decode

### ISSUE THREAD

**Issue by stephenafamo** [sethvargo/go-envconfig#13]
Any struct fields that come after a custom decodable field are ignored

See: https://play.golang.org/p/b-RG2bCVLP2

**Comment by sethvargo** [comment]
The joys of reflection 😄 

Thanks for catching these. Fixed in https://github.com/sethvargo/go-envconfig/pull/14. Since you're already making go playground links (which is super helpful), do you want to submit PRs to add failing tests? I created a new section for issue-specific tests to demonstrate failures and prevent regressions.

**Comment by stephenafamo** [comment]
Sure. I'll add them if I find anything else 😄
