### ISSUE TITLE
Overwrite and required 

### ISSUE THREAD

**Issue by FedorLap2006** [sethvargo/go-envconfig#70]
When using environment configuration as an override to a file-based configuration (e.g. viper w/yaml), the field needs to overwrite the existing when present in environment variables, use existing value if it is non-zero, and error if the value is both zero and not present in the configuration.

Currently `overwrite` makes `required` error when the field is non-zero, but not present in the environment variables.

**Comment by sethvargo** [comment]
Hi @FedorLap2006 

Thank you for opening an issue. The ["contract" for required](https://github.com/sethvargo/go-envconfig#required) is:

> If a field is required, processing will error if the environment variable is unset.

So I think this is behaving as intended. Changing this semantic would be a little weird, because it's not possible to differentiate between a field set to the zero value vs a field unset. For example, consider a string field:

```go
type MyStruct struct {
  Field string `env:"FIELD,required"`
}
```

By default, envconfig will error. However, if the environment variable is set to the empty string (`export FIELD=""`), this will succeed. In other words, `required` says "the environment variable must be set". It does **not** say "the struct field must be set".
