### ISSUE TITLE
Only works if env is the first tag in Multiple Tags Field

### ISSUE THREAD

**Issue by eopeter** [sethvargo/go-envconfig#89]
if you have a struct where `env` is not the first tag such as the following, it does not get the value from the environment and does not error:

```
type DatabaseConfig struct {
        Host   string `yaml:"host" ,env:"MYSQL_HOST,required"`
	Port     int    `yaml:"port" ,env:"MYSQL_PORT,required"`
}
```

It works if you have:
```
type DatabaseConfig struct {
	Host  string `env:"MYSQL_HOST,required" ,yaml:"host"`
	Port   int    `env:"MYSQL_PORT,required" ,yaml:"port"`
}
```

**Comment by sethvargo** [comment]
Hi @eopeter - this has nothing to do with envconfig. You are not using [Go structure tags](https://go.dev/ref/spec#Struct_types) correctly. Per [the documentation](https://pkg.go.dev/reflect#StructTag):

> By convention, tag strings are a concatenation of optionally space-separated key:"value" pairs. Each key is a non-empty string consisting of non-control characters other than space (U+0020 ' '), quote (U+0022 '"'), and colon (U+003A ':'). Each value is quoted using U+0022 '"' characters and Go string literal syntax.

In short, the separator between struct tags is a space, not a comma. In this example:

```go
type DatabaseConfig struct {
  Host string `yaml:"host" ,env:"MYSQL_HOST,required"`
  Port int    `yaml:"port" ,env:"MYSQL_PORT,required"`
}
```

You have two struct tag keys: `yaml` and `,env` (note the key is ",env", not "env").

In this example:

```go
type DatabaseConfig struct {
  Host string `env:"MYSQL_HOST,required" ,yaml:"host"`
  Port int    `env:"MYSQL_PORT,required" ,yaml:"port"`
}
```

You have two struct tag keys: `,yaml` and `env` (note the key is "env", not ",env"). Your second example would fail to parse as YAML though, since it isn't actually defining a YAML key.

The correct structure is:

```go
type DatabaseConfig struct {
  Host string `env:"MYSQL_HOST,required" yaml:"host"`
  Port int    `env:"MYSQL_PORT,required" yaml:"port"`
}
```

**Comment by eopeter** [comment]
Ahh! Thank you !
